export const workshopDataPlaceholder = [
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Esto deberia de estar en la pagina do2',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Esto deberia de estar en la pagina do2',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Derechos Humanos',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '01/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
  {
    title: 'Liderazgo',
    first_names: 'Luis',
    last_names: 'Lopez',
    start_date: '12/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Presentaciones efectivas',
    first_names: 'Sandy',
    last_names: 'Medrano',
    start_date: '2/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'Asistio',
  },
  {
    title: 'Bioetica',
    first_names: 'Sherman',
    last_names: 'Commendador',
    start_date: '10/08/2023',
    end_date: '01/08/2023',
    pensum: 'Ciudadania',
    modality: 'Presencial',
    platform: 'Oficinas de AVAA',
    year: 'I',
    scholarAttendance: 'No asistio',
  },
];
